- frontend/jobBoard.css
- frontend/jobBoard.js
- frontend/sidebar.css
- frontend/sidebar.js
> Displaying Temp Data w/ Board and Card + Styling

- backend/package-lock.json
- backend/routers/applicationRouter.js
- backend/routers/userRouter.js
- backend/server.js
- backend/users/userModel.js
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Complete, tested, ready to review and merge
This has been tested with chrome and console logs. Further testing will be needed once functionality is added.
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My code has been reviewed by at …
> Organization of routes complete. userModel needs updates from Robert.

- .gitignore
- backend/config/database.config.js
- backend/config/redis.config.js
- backend/package-lock.json
- backend/package.json
- backend/routers/userRouter.js
- backend/server.js
> implemented session store + redis

- frontend/src/components/jobboard/jobboard.js
- frontend/src/components/jobboard/jobcontainer.js
> Functioning Card and Board Movement

- backend/config/config.js
- backend/package-lock.json
- backend/package.json
- backend/server.js
> enabled cors

- backend/readme.md
- backend/routers/applicationRouter.js
- backend/routers/contributionsRouter.js
- backend/routers/meetupsRouter.js
- backend/routers/userRouter.js
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Complete, tested, ready to review and merge
tested with Postman
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I …
> Fixed errors in readme. Made endpoint responses more consistent

- backend/config/config.js
- backend/models/applicationModel.js
- frontend/package.json
- frontend/public/index.html
- frontend/src/components/accountlogin/accountlogin.js
- frontend/src/components/billing/billing.css
- frontend/src/components/billing/billing.js
- frontend/src/components/billing/checkoutform.js
- frontend/src/components/jobboard/jobboard.js
- frontend/src/index.js
- frontend/yarn.lock
> added initial stripe front-end

- backend/config/config.js
- frontend/src/components/accountlogin/accountlogin.css
- frontend/src/components/accountlogin/accountlogin.js
- frontend/src/components/accountsignup/accountsignup.css
- frontend/src/components/accountsignup/accountsignup.js
- frontend/src/components/meetup/meetup.js
Signup/login modals were updated. Login after successful signup was added as well as redirection to /jobs after successful login
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Complete, tested, ready to review and merge
It was tested in the browser
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own …
> Updated login/signup modals. Added login after signup and redirection to /jobs

- backend/config/config.js
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] Complete, tested, ready to review and merge
This PR is reverting back to working code changed in error.
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] My code has been reviewed by at least one peer
- [ x] I have commented my code, particularly …
> fixed cors setting changed in error on last PR

- backend/stripe/stripe.js
- frontend/src/components/billing/checkoutform.js
> Response from subscription working

- backend/routers/applicationRouter.js
- backend/routers/contributionsRouter.js
- backend/routers/meetupsRouter.js
- backend/routers/userRouter.js
- frontend/package-lock.json
- frontend/src/components/accountlogin/accountlogin.js
- frontend/src/components/jobcreatemodal/jobcreatemodal.css
- frontend/src/components/jobcreatemodal/jobcreatemodal.js
connected createjobsmodal to the API. Fixed scroll bar on modal. called handJobCreation method from jobs.js
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Complete, tested, ready to review and merge
tested in browser
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My code has been …
> Connected createjobsmodal to API

- frontend/src/pages/jobs.js
- routers/userRouter.js
login endpoint no longer requires an email
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] Complete, tested, ready to review and merge
through local frontend and postman
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [x ] I have commented my …
> fixed bug with login

- frontend/package.json
- frontend/src/components/accountlogin/accountlogin.js
- frontend/src/components/accountsignup/accountsignup.js
- frontend/src/components/signout/signout.js
- frontend/src/history.js
- frontend/src/index.js
- frontend/src/pages/billing.js
- frontend/src/pages/contributions.js
- frontend/src/pages/home.js
- frontend/src/pages/jobs.js
- frontend/src/pages/meetups.js
- frontend/src/pages/settings.js
Bug fix involving creating a history object and importing it into components that need it.
> Properly setup history prop

- frontend/src/pages/billing.js
- frontend/src/pages/contributions.js
- frontend/src/pages/home.js
- frontend/src/pages/meetups.js
- frontend/src/pages/settings.js
Converted props to functional variety.
> Fixed props

- config/config.js
- frontend/src/config/config.js
- frontend/src/index.js
> Quilly rendering on Netlify

- frontend/src/components/billing/billing.css
- frontend/src/components/billing/billing.js
- frontend/src/components/billing/checkoutform.js
- frontend/src/components/contribution/contribution.css
- frontend/src/components/jobcreatemodal/jobcreatemodal.css
- frontend/src/components/jobcreatemodal/jobcreatemodal.js
- frontend/src/components/meetup/meetup.css
- frontend/src/components/settings/settings.css
- frontend/src/index.css
- frontend/src/pages/billing.js
- frontend/src/pages/contributions.js
- frontend/src/pages/jobs.js
- frontend/src/pages/meetups.js
- frontend/src/pages/settings.js
> uniform styling, added page titles among other things

- frontend/src/App.js
Users shouldn't have to log in every time they visit. This makes things more convenient by routing them where they should go.
> Added auto-routing to main jobs page for authenticated users

- frontend/src/components/accountlogin/accountlogin.css
- frontend/src/components/accountsignup/accountsignup.css
- frontend/src/components/jobboard/jobboard.css
- frontend/src/components/jobcreatemodal/jobcreatemodal.css
- frontend/src/components/jobcreatemodal/jobcreatemodal.js
- frontend/src/components/jobdeletemodal/jobdeletemodal.css
- frontend/src/index.css
- frontend/src/pages/home.js
The jobs board now no longer has its own background. The landing page is responsive. The modals are now opaque.
> Fixed background on jobs board and made landing page responsive

- frontend/src/components/accountlogin/accountlogin.js
- frontend/src/components/contribution/contribution.css
- frontend/src/components/contribution/contribution.js
- frontend/src/components/meetup/meetup.css
- frontend/src/components/meetup/meetup.js
> Consistent styling for meetup and contribution, small background color change for login btn onclick

- frontend/src/components/accountlogin/accountlogin.js
- frontend/src/index.css
- frontend/src/pages/home.js
Made some tweaks and improved responsiveness. 
> Updated styling on landing page

- frontend/src/components/accountlogin/accountlogin.js
Updated login button to properly update text.
> Fixed login button

- frontend/src/components/accountlogin/accountlogin.js
> Fixing login bug.

- frontend/src/App.js
- frontend/src/components/accountlogin/accountlogin.js
- frontend/src/components/billing/billing.css
- frontend/src/components/billing/billing.js
- frontend/src/components/billing/checkoutform.js
- frontend/src/components/contribution/contribution.css
- frontend/src/components/contribution/contribution.js
- frontend/src/components/jobboard/jobboard.css
- frontend/src/components/jobboard/jobboard.js
- frontend/src/components/jobcreatemodal/jobcreatemodal.css
- frontend/src/components/jobcreatemodal/jobcreatemodal.js
- frontend/src/components/meetup/meetup.css
- frontend/src/components/meetup/meetup.js
- frontend/src/components/resumeView/resumeView.css
- frontend/src/components/settings/settings.css
- frontend/src/components/settings/settings.js
- frontend/src/components/sidebar/sidebar.css
- frontend/src/components/sidebar/sidebar.js
- frontend/src/components/signout/signout.css
- frontend/src/config/config.js
- frontend/src/index.css
- frontend/src/pages/billing.js
- frontend/src/pages/contributions.js
- frontend/src/pages/home.js
- frontend/src/pages/introductions.js
- frontend/src/pages/jobs.js
- frontend/src/pages/meetups.js
- frontend/src/pages/resumes.js
- frontend/src/pages/settings.js
Added various changes to make the site relatively usable even on smaller devices.
> Finished making site responsive

- frontend/src/components/jobboard/jobboard.css
- frontend/src/components/meetup/meetup.css
- frontend/src/index.css
Had an issue with background not displaying properly which required changing page height values.
> Last minute adjustments to fix background on jobs page
